trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm install -g rimraf gulp-cli tslint
  displayName: 'Global dependencies'

- script: |
    npm ci
    npm run build
  displayName: 'Dependencies & Build'

- script: npm run test
  displayName: 'Run tests'
  timeoutInMinutes: 10
